// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrs14xaT4JMj0e9x9jZ2-I0MpRAFSbQhw',
    appId: '1:650216056799:web:bc59b1d745e9ad1a02866a',
    messagingSenderId: '650216056799',
    projectId: 'zen-assist-app-ab614',
    authDomain: 'zen-assist-app-ab614.firebaseapp.com',
    storageBucket: 'zen-assist-app-ab614.firebasestorage.app',
    measurementId: 'G-KYRXYRY6RX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMss2fXbkyJwJ7nndUy9cJYCatEiLMl3E',
    appId: '1:650216056799:android:b8b0b7a6073bf16802866a',
    messagingSenderId: '650216056799',
    projectId: 'zen-assist-app-ab614',
    storageBucket: 'zen-assist-app-ab614.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqPb6LTRpjuv3oo6DgvRCCSVnfkkn4XZU',
    appId: '1:650216056799:ios:08656d52b23edde402866a',
    messagingSenderId: '650216056799',
    projectId: 'zen-assist-app-ab614',
    storageBucket: 'zen-assist-app-ab614.firebasestorage.app',
    iosBundleId: 'com.example.zenAssist',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqPb6LTRpjuv3oo6DgvRCCSVnfkkn4XZU',
    appId: '1:650216056799:ios:08656d52b23edde402866a',
    messagingSenderId: '650216056799',
    projectId: 'zen-assist-app-ab614',
    storageBucket: 'zen-assist-app-ab614.firebasestorage.app',
    iosBundleId: 'com.example.zenAssist',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCrs14xaT4JMj0e9x9jZ2-I0MpRAFSbQhw',
    appId: '1:650216056799:web:2dee8d84c468145b02866a',
    messagingSenderId: '650216056799',
    projectId: 'zen-assist-app-ab614',
    authDomain: 'zen-assist-app-ab614.firebaseapp.com',
    storageBucket: 'zen-assist-app-ab614.firebasestorage.app',
    measurementId: 'G-C8X4NGBXZP',
  );
}
